version: 2
sources:
  - name: raw
    description: Raw data loaded from NYC Open Data
    database: qianchen-cis-4400-f7
    schema: nyc_311_raw_data 
    tables:
      - name: source_311nyc_Dog_Complaints
        description: |
          NYC 311 complaints for dog
          One row per complaint.
        columns:
          - name: unique_key
            description: Unique ID for the service request
            tests:
              - unique
              - not_null
          - name: created_date
            description: Date and time the request was created
          - name: closed_date
            description: Date and time the request was closed
          - name: agency
            description: Agency code
          - name: agency_name
            description: Full name of the agency
          - name: complaint_type
            description: Type of complaint
          - name: descriptor
            description: Further description of the complaint
          - name: location_type
            description: Location where the incident occurred
          - name: incident_zip
            description: Zip code of the incident location
          - name: incident_address
            description: Street address of the incident
          - name: latitude
            description: Latitude coordinate
          - name: longitude
            description: Longitude coordinate
          - name: address_type
            description: 'Type of address (e.g., ADDRESS, INTERSECTION, BLOCKFACE)'
          - name: bbl
            description: Borough Block and Lot number (NYC tax lot id)
          - name: borough
            description: NYC borough where incident occurred
          - name: city
            description: City name where incident occurred
          - name: community_board
            description: NYC Community Board district number
          - name: council_district
            description: district where incident occurred
          - name: cross_street_1
            description: First cross street near incident location
          - name: cross_street_2
            description: Second cross street near incident location
          - name: descriptor_2
            description: additional description of the complaint
          - name: facility_type
            description: Type of facility where incident occurred
          - name: intersection_street_1
            description: First street forming intersection where incident occurred
          - name: intersection_street_2
            description: Second street forming intersection where incident occurred
          - name: landmark
            description: nearby landmark
          - name: open_data_channel_type
            description: how complaints where file
          - name: park_borough
            description: Borough of park where incident occurred
          - name: park_facility_name
            description: Name of park facility where incident occurred
          - name: police_precinct
            description:  police_precinct number
          - name: resolution_action_updated_date
            description: Date when resolution action was last updated
          - name: resolution_description
            description: Description of how the request was resolved
          - name: status
            description: Current status of complaint (Open, Closed, In Progress, etc.)
          - name: street_name
            description: Name of street where incident occurred
          - name: x_coordinate_state_plane
            description: X coordinate in NY State Plane projection system (NAD 83)
          - name: y_coordinate_state_plane
            description: Y coordinate in NY State Plane projection system (NAD 83)
          - name: bridge_highway_direction
            description: Direction on bridge or highway (e.g. Northbound)
          - name: bridge_highway_name
            description: Name of bridge or highway where incident occurred
          - name: bridge_highway_segment
            description: Specific segment of bridge or highway
          - name: road_ramp
            description: Road ramp identifier where incident occurred

      - name: source_nyc_dog_licensing
        description: |
          Raw data for NYC dog licensing
        columns:
          - name: animalname
            description: User-provided dog name
          - name: animalgender
            description: M (Male) or F (Female) dog gender
          - name: animalbirth
            description: Year dog was born
          - name: breedname 
            description: dog breed
          - name: zipcode
            description: owner's zipcode
          - name: licenseissueddate
            description: Date the dog license was issued
          - name: licenseexpireddate
            description: Date the dog license expires
          - name: extract_year
            description: The year this record was extracted

      - name: source_Animal_Characteristics
        description: |
          Raw data for aninal charateristics
        columns:
          - name: breedname 
            description: dog breed
          - name: size_category
            description: animal size (small, mid, larger)
          - name: temperament
            description: animal's temperament